name: Ready the code and deploy

on: [push, workflow_dispatch]

jobs:
     test-code:
          runs-on: ubuntu-latest
          steps:
            - name: copying the codes
              uses: actions/checkout@v4

            - name: installing node
              uses: actions/setup-node@v4

            - name: check the node version
              run: node -v

            - name: install dependencies
              run: npm install --frozen-lockfile

            - name: check the dependencies
              run: npm list

            # - name: Run the tests
            #   run: npm test
     build-code:
          runs-on: ubuntu-latest    
          steps:
            - name: installing node
              uses: actions/setup-node@v4

            - name: copying the codes
              uses: actions/checkout@v4

            - name: check the node version              
              run: node -v

            - name: install dependencies
              run: npm install --frozen-lockfile

            - name: build the code
              run: npm run build   
     deploy-code:
          runs-on: ubuntu-latest
          steps:
            - name: Deploy the codes
              run : echo "deploying...."
