name: Ready the code and deploy

on: [push, workflow_dispatch]

jobs:
     test-code:
          runs-on: ubuntu-latest
          steps:
            - name: copying the codes
              uses: actions/checkout@v4
            - name: installing node
              uses: actions/setup-node@v4
            - name: check the node version
              run: node -v
             
